### ISSUE TITLE
Support Spring Message Resources

### ISSUE THREAD

**Issue by A-pZ** [A-pZ/struts2-thymeleaf3-plugin#29]

**Comment by psyuhen** [comment]
https://github.com/psyuhen/struts2-thymeleaf3-plugin/tree/develop/1.0.5.1

看看这个，在原来的1.0.5的版本基础上解决了没有加struts2的资源文件的问题。

**Comment by A-pZ** [comment]
@psyuhen Great work!! 
I'll release for your changes with Struts2.5.17. However, Struts2.5.17 changes LocalTextProvider to StrutsLocalizedTextProvider ( LocalTextProvider was deleted 2.5.17 ), and then I changed LocalTextProvider ,
